services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_DB=finance'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped